#!/usr/bin/env python3
"""Provider abstraction for generated media backends.

The no-Atlas workflow defaults to Agnes for image-to-video. Keyframes are created
outside Python with Codex imagegen, then uploaded to imgw.cc by scripts/agnes.py.
Audio is local-file based and does not go through this provider layer.
"""
import time
from abc import ABC, abstractmethod

import agnes


class ProviderError(RuntimeError):
    pass


class Provider(ABC):
    """The surface the stages need. get_status normalizes every backend's polling
    response to {status: pending|completed|failed, output: <url|None>, error}."""
    name = "base"

    @abstractmethod
    def submit_image(self, model, prompt, **params): ...
    @abstractmethod
    def submit_video(self, model, prompt, **params): ...
    @abstractmethod
    def submit_audio(self, model, **params): ...
    @abstractmethod
    def remove_bg(self, model, image_url, **params): ...
    @abstractmethod
    def get_status(self, job_id): ...
    @abstractmethod
    def upload(self, path): ...
    @abstractmethod
    def download(self, url, dest): ...


class AgnesProvider(Provider):
    """Video backend for Agnes AI.

    Keyframes are generated by Codex imagegen and supplied as local paths or
    public HTTPS URLs. Local paths are uploaded through imgw.cc.
    """
    name = "agnes"

    def submit_image(self, model, prompt, **params):
        raise ProviderError(
            "Image generation is handled by Codex imagegen, not provider.py. "
            "Run keyframes.py to export prompts, generate images with imagegen, "
            "then set shot.keyframe_path or shot.keyframe_url."
        )

    def submit_video(self, model, prompt, **params):
        return agnes.submit_video(model, prompt, **params)

    def submit_audio(self, model, **params):
        raise ProviderError("Audio is local-file based in the no-Atlas workflow; use scripts/audio.py to validate paths.")

    def remove_bg(self, model, image_url, **params):
        raise ProviderError("Agnes remove-bg is not wired in this workflow.")

    def get_status(self, job_id):
        return agnes.get_status(job_id)

    def upload(self, path):
        return agnes.upload(path)

    def download(self, url, dest):
        return agnes.download(url, dest)


_REGISTRY = {"agnes": AgnesProvider}


def get_provider(name=None):
    """Return a Provider instance by name (default 'agnes')."""
    name = (name or "agnes").lower()
    if name not in _REGISTRY:
        raise ProviderError(f"unknown provider '{name}'; available: {list(_REGISTRY)}")
    return _REGISTRY[name]()


def run_jobs(prov, specs, *, poll_s=3, stall_s=90, max_retries=2, deadline_s=900):
    """Submit + poll a batch of jobs, resubmitting any that FAIL or STALL.

    specs: dict of key -> submit() callable returning a job id. A job that fails,
    or stays pending past `stall_s`, is resubmitted (fresh id) up to `max_retries`
    times — this is what stops one stuck prediction from wasting the whole deadline.
    Returns key -> output URL (or None). Prints progress like the old loops did.
    """
    st = {}
    for key, submit in specs.items():
        st[key] = {"pid": submit(), "t": time.time(), "tries": 0}
        print(f"[{key}] submitted {st[key]['pid']}")

    done = {}
    deadline = time.time() + deadline_s
    while len(done) < len(specs) and time.time() < deadline:
        time.sleep(poll_s)
        now = time.time()
        for key, submit in specs.items():
            if key in done:
                continue
            s = st[key]
            r = prov.get_status(s["pid"])
            status = r["status"]
            if status == "completed":
                done[key] = r["output"]
                print(f"[{key}] done")
            elif status == "failed" or (status == "pending" and now - s["t"] > stall_s):
                if s["tries"] < max_retries:
                    s["tries"] += 1
                    s["pid"] = submit()
                    s["t"] = time.time()
                    why = "failed" if status == "failed" else f"stalled>{int(stall_s)}s"
                    print(f"[{key}] {why} -> resubmit #{s['tries']} ({s['pid']})")
                elif status == "failed":
                    done[key] = None
                    print(f"[{key}] FAILED: {(r.get('error') or '')[:120]}")
                # stalled + out of retries: keep waiting until the deadline
    for key in specs:
        done.setdefault(key, None)
    return done
